apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground
  namespace: dev
  labels:
    app: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: grade1-api
        image: wil42/playground:v1
        ports:
          - containerPort: 8888
