apiVersion: apps/v1
kind: Deployment
metadata:
  replicas: 2
  name: will-playground
  namespace: dev
  labels:
    app: grade1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade1
  template:
    metadata:
      labels:
        app: grade1
    spec:
      containers:
      - name: grade1-api
        image: wil42/playground:v1
        ports:
          - containerPort: 8888
