apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade1-api
  namespace: grade2
  labels:
    app: grade1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade1
    template:
      metadata:
        labels:
          app: grade1
      spec:
        containers:
        - name: grade1-api
          image: wil42/playground:v1
          ports:
            - containerPort: 8888